### ISSUE TITLE
Chinmaya_19HCS4013

### ISSUE THREAD

**Issue by Chinmayabhoi** [p06p05/java_programs_5_to10#35]
[CHINMAYA_19HCS4013.zip](https://github.com/p06p05/java_programs_5_to10/files/4375451/CHINMAYA_19HCS4013.zip)

**Comment by sonu1234indian** [comment]
[SONU YADAV 19HCS4072.zip](https://github.com/p06p05/java_programs_5_to10/files/4375577/SONU.YADAV.19HCS4072.zip)
